package consts

const (
	HeaderContentType                      = "Content-Type"
	HeaderContentLength                    = "Content-Length"
	HeaderAccept                           = "Accept"
	HeaderAcceptEncoding                   = "Accept-Encoding"
	HeaderAcceptLanguage                   = "Accept-Language"
	HeaderAuthorization                    = "Authorization"
	HeaderCacheControl                     = "Cache-Control"
	HeaderConnection                       = "Connection"
	HeaderCookie                           = "Cookie"
	HeaderDate                             = "Date"
	HeaderHost                             = "Host"
	HeaderIfNoneMatch                      = "If-None-Match"
	HeaderIfRange                          = "If-Range"
	HeaderIfUnmodifiedSince                = "If-Unmodified-Since"
	HeaderLastModified                     = "Last-Modified"
	HeaderLocation                         = "Location"
	HeaderOrigin                           = "Origin"
	HeaderPragma                           = "Pragma"
	HeaderRange                            = "Range"
	HeaderReferer                          = "Referer"
	HeaderServer                           = "Server"
	HeaderSetCookie                        = "Set-Cookie"
	HeaderTransferEncoding                 = "Transfer-Encoding"
	HeaderUpgrade                          = "Upgrade"
	HeaderUserAgent                        = "User-Agent"
	HeaderVary                             = "Vary"
	HeaderWWWAuthenticate                  = "WWW-Authenticate"
	HeaderXContentTypeOptions              = "X-Content-Type-Options"
	HeaderXFrameOptions                    = "X-Frame-Options"
	HeaderXForwardedFor                    = "X-Forwarded-For"
	HeaderXForwardedHost                   = "X-Forwarded-Host"
	HeaderXForwardedProto                  = "X-Forwarded-Proto"
	HeaderXRealIP                          = "X-Real-IP"
	HeaderXRequestedWith                   = "X-Requested-With"
	HeaderXUACompatible                    = "X-UA-Compatible"
	HeaderXWebKitCSP                       = "X-WebKit-CSP"
	HeaderXContentSecurityPolicy           = "X-Content-Security-Policy"
	HeaderXPermittedCrossDomainPolicies    = "X-Permitted-Cross-Domain-Policies"
	HeaderXDownloadOptions                 = "X-Download-Options"
	HeaderXRobotsTag                       = "X-Robots-Tag"
	HeaderXDNSPrefetchControl              = "X-DNS-Prefetch-Control"
	HeaderXContentSecurityPolicyReportOnly = "X-Content-Security-Policy-Report-Only"
	HeaderXFrameOptionsReportOnly          = "X-Frame-Options-Report-Only"

	HeaderMimeTypeCSS           = "text/css"
	HeaderMimeTypeCSSGZ         = "text/css+gzip"
	HeaderMimeTypeCSVGZ         = "text/csv+gzip"
	HeaderMimeTypeCSVGZUTF8     = "text/csv+gzip; charset=utf-8"
	HeaderMimeTypeCSVUTF8       = "text/csv; charset=utf-8"
	HeaderMimeTypeCSV           = "text/csv"
	HeaderMimeTypeHTML          = "text/html"
	HeaderMimeTypeHTMLGZ        = "text/html+gzip"
	HeaderMimeTypeHTMLGZUTF8    = "text/html+gzip; charset=utf-8"
	HeaderMimeTypeHTMLUTF8      = "text/html; charset=utf-8"
	HeaderMimeTypeJS            = "text/javascript"
	HeaderMimeTypeJSON          = "application/json"
	HeaderMimeTypeJSONGZ        = "application/json+gzip"
	HeaderMimeTypeJSONGZUTF8    = "application/json+gzip; charset=utf-8"
	HeaderMimeTypeJSONUTF8      = "application/json; charset=utf-8"
	HeaderMimeTypeText          = "text/plain"
	HeaderMimeTypeTextGZ        = "text/plain+gzip"
	HeaderMimeTypeTextGZUTF8    = "text/plain+gzip; charset=utf-8"
	HeaderMimeTypeTextUTF8      = "text/plain; charset=utf-8"
	HeaderMimeTypeTextHTML      = "text/html; charset=utf-8"
	HeaderMimeTypeTextXML       = "text/xml; charset=utf-8"
	HeaderMimeTypeXML           = "text/xml"
	HeaderMimeTypeAny           = "*/*"
	HeaderMimeTypeForm          = "application/x-www-form-urlencoded"
	HeaderMimeTypeMultipartForm = "multipart/form-data"
	HeaderMimeTypeOctetStream   = "application/octet-stream"
	HeaderMimeTypeImage         = "image/*"
	HeaderMimeTypeImagePNG      = "image/png"
	HeaderMimeTypeImageGIF      = "image/gif"
	HeaderMimeTypeImageWebP     = "image/webp"
	HeaderMimeTypeImageHEIC     = "image/heic"
	HeaderMimeTypeImageHEIF     = "image/heif"
	HeaderMimeTypeImageTGA      = "image/tga"
	HeaderMimeTypeImageTIFF     = "image/tiff"
	HeaderMimeTypeImageWEBP     = "image/webp"
	HeaderMimeTypeImageJPG      = "image/jpg"
	HeaderMimeTypeImageJPEG     = "image/jpeg"
	HeaderMimeTypeImageJPE      = "image/jpe"
	HeaderMimeTypeImageJFIF     = "image/jfif"
	HeaderMimeTypeImageBMP      = "image/bmp"
	HeaderMimeTypeImageICO      = "image/ico"
	HeaderMimeTypeImageSVG      = "image/svg+xml"
	HeaderMimeTypeImageSVGZ     = "image/svg+xml+gzip"
	HeaderMimeTypeImageAVIF     = "image/avif"
	HeaderMimeTypeImageAVIFS    = "image/avif-sequence"
)
